// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtTqKSKkJmrl8tAuiubkJexXi7mz9jwuk',
    appId: '1:869254644530:android:8870c648d7387fe5870d2b',
    messagingSenderId: '869254644530',
    projectId: 'fir-7637a',
    storageBucket: 'fir-7637a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXbh8tNDn30DeAcVkUtM3uBw33Okh_wTE',
    appId: '1:869254644530:ios:15e64676b044e9f7870d2b',
    messagingSenderId: '869254644530',
    projectId: 'fir-7637a',
    storageBucket: 'fir-7637a.appspot.com',
    androidClientId: '869254644530-aa7jvmp9mp0911hff5ibuk4rqsei1201.apps.googleusercontent.com',
    iosClientId: '869254644530-povtmk8g14o7d419438ltkm257ak3vgg.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseOfflineDemo',
  );
}
